# Spring Boot Application Configuration Template
spring:
  application:
    name: ${SERVICE_NAME:service-template}

  config:
    activate:
      on-profile: "mysql"

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:servicedb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

---
# PostgreSQL Configuration
spring:
  config:
    activate:
      on-profile: "postgres"

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:servicedb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

---
# MongoDB Configuration
spring:
  config:
    activate:
      on-profile: "mongodb"

  data:
    mongodb:
      uri: mongodb://localhost:27017/${DB_NAME:servicedb}
      auto-index-creation: true

# Disable JPA for MongoDB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

---
# Common Configuration (applies to all profiles)
spring:
  cloud:
    config:
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always

# Logging
logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFOspring.profiles.active=mysql
